### PR TITLE
chore: consistent naming

### PR DESCRIPTION
**Pull request by azjezz**

### CODE REVIEW

**Comment by azjezz** [comment]
p.s: i had to manually update the ast.txt in all tests, but with #134, i just need to run the new binary :D

**Comment by ryangjchandler** [comment]
Can we flip the order, so `StringLiteral`, etc?

**Comment by azjezz** [comment]
i think `literal` followed by the type makes more sense, it is also the format used by phpstan, and psalm ( e.g https://psalm.dev/docs/annotating_code/type_syntax/scalar_types/#literal-string )

**Comment by ryangjchandler** [comment]
Meh, yeah okay. If that's what PHPStan/Psalm uses, let's go with it.

**Pull request merged**
